### ISSUE TITLE
Deprecate Able when Kable is released

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/able#91]
[Kable](https://github.com/JuulLabs/kable) will be multiplatform and supersede Able, providing a more powerful yet simpler API.

**Comment by subvertallchris** [comment]
This looks awesome! Any thoughts on when Kable will be stable and released?

**Comment by twyatt** [comment]
> This looks awesome!

Thanks!

> Any thoughts on when Kable will be stable and released?

It's getting really close, some remaining tasks:

- Implement JavaScript scanner support (https://github.com/JuulLabs/kable/pull/23)
- Implement JavaScript `rssi` support
- Clean up the API a bit (https://github.com/JuulLabs/kable/pull/24)
- General code clean up including https://github.com/JuulLabs/kable/issues/6

...then it should be ready for a `0.1.0` release. I'd estimate another week or two. 🤞 

The API probably won't be a "stable" for a while (i.e. subject to change based on community feedback) but we've done a lot of work to keep the API simple, so hopefully it won't need to change too much. As for being stable, we've done a fair amount of testing using https://github.com/JuulLabs/sensortag sample app, so it should be ready for use (maybe not quite production worthy yet, as it hasn't been used a ton, yet). We'll be integrating Kable into our apps soon though, where it will get a lot more use/testing.

**Comment by subvertallchris** [comment]
Awesome, I'll be looking forward to it! I hacked in a simple peripheral using Able this morning, it's working like a dream. I spent all day yesterday making sense of the Android BLE libraries (I'm not an Android dev, I just play one on TV) and the callbacks were just brutal. Glad I started there so I can appreciate what you've done here. Thanks for all your hard work!

**Comment by twyatt** [comment]
> I hacked in a simple peripheral using Able this morning, it's working like a dream.

Glad to hear!

> I spent all day yesterday making sense of the Android BLE libraries

Ya, BLE in general is complex, then Android's BLE framework didn't help matters at all. Making Able was a huge learning experience for us. I'm hoping [Kable](https://github.com/JuulLabs/kable) makes BLE very approachable even for people new to BLE.

> I'm not an Android dev, I just play one on TV

Haha! 😄 

> Thanks for all your hard work!

You're very welcome, always awesome to hear others finding it useful.

**Comment by twyatt** [comment]
[Kable] `0.1.0` has been released and is available on `mavenCentral` / `jcenter`. 🎉 

[Kable]: https://github.com/JuulLabs/kable
